<?php
//
// +----------------------------------------------------------------------+
// | PHP Version 4                                                        |
// +----------------------------------------------------------------------+
// | Copyright (c) 2009 - 2010 Joshua La Force                            |
// +----------------------------------------------------------------------+
// | This source file is subject to version 2.02 of the PHP license,      |
// | that is bundled with this package in the file LICENSE, and is        |
// | available at through the world-wide-web at                           |
// | http://www.php.net/license/2_02.txt.                                 |
// | If you did not receive a copy of the PHP license and are unable to   |
// | obtain it through the world-wide-web, please send a note to          |
// | license@php.net so we can mail you a copy immediately.               |
// +----------------------------------------------------------------------+
// | Author: Joshua La Force <josh@laforce.com                            |
// +----------------------------------------------------------------------+
//
// $Id: config.inc v 1.0 2010/02/15 03:41:18 jlf Exp $

/**
* Config information for MySQL db access
*
* @file config.inc
* @note replace the settings below with your MySQL settings
**/

define('DB_HOSTNAME','massage2u.db.5700694.hostedresource.com');
define('DB_USERNAME','massage2u');
define('DB_PASSWORD','ADr9pj7ByIeZUM');
define('DB_DATABASE','massage2u');

?>