<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Massage 2 U, LLC</title>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<meta name="Keywords" content="sports therapist, massage gift certificates, rmt houston, massage rates, best massage houston, lmt houston, deeptissue massage therapist, deep tissue massage therapy, massage houston galleria, swedish massage therapy, houston sports massage, gay houston massage, sports massage therapy, deep tissue massage houston, gay massage, gay massage therapist, gay massage therapist houston tx, gay massage therapist houston, licensed massage therapist, licensed massage therapist houston, registered massage therapist, sports massage, sports massage therapist, deep tissue massage, deep tissue massage houston, Galleria, Houston, Houston therapeutic massage, massage houston, houston massage, massaage therapy houston, massage houston tx, massagers houston, massage houston texas, houston massage reviews, male massage therapist, houston massage spa, massage houston midtown, massage midtown, montrose massage, montrose massage houston, montrose massage therapist" />
<meta name="Description" content="Zeppelin Massage therapy LMT provides Sports Massage, deep tissue massage, and swedish massage services at a relaxing studio located in the Houston tx Montrose area.  Please read my massage therapist reviews, check my massage rates.  Massage gift certificates are available" />
<link rel="stylesheet" href="m2u-style.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script src="m2u-script.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="mouseovertabs.css" />
<script src="mouseovertabs.js" type="text/javascript"></script>
</head>

<body>
<div id="admin_logo_home"><img src="images/m2u-admin-logo.gif" alt="Massage 2 U, LLC Logo | Houston TX 77006" height="100" width="139" /></div>

<?php if ($_SESSION['logged_in']) { include_once("menu-admin.inc"); } ?>

<div id="content_div">
<!-- begin content div -->
