<div id="common_btn_menu" name="common_btn_menu">
<img src="images/blank.gif" alt="" height="50" width="131" />
<br /><br /><br />
<a href="index.php" title="home"><img src="images/btn-home.gif" name="home" alt="home" height="31" width="131" border="0" onmouseover="display(1);" onmouseout="display(0);" /></a><br />
<a href="servicearea.php" title="service area"><img src="images/btn-svcarea.gif" name="servicearea" alt="service area" height="31" width="131" border="0" onmouseover="display(3);" onmouseout="display(2);" /></a><br />
<a href="rates.php" title="rates/hours"><img src="images/btn-rates.gif" alt="rates/hours" name="rates" height="31" width="131" border="0" onmouseover="display(5);" onmouseout="display(4);" /></a><br />
<a href="therapists.php" title="therapists"><img src="images/btn-therapists.gif" name="therapists" alt="therapists" height="31" width="131" border="0" onmouseover="display(7);" onmouseout="display(6);" /></a><br />
<a href="appointments.php" title="Book Online!"><img src="images/btn-bookonline.gif" name="appointments" alt="Book Online" height="31" width="131" border="0" onmouseover="display(9);" onmouseout="display(8);" /></a><br />
<a href="aboutus.php" title="about us"><img src="images/btn-aboutus.gif" name="about" alt="about us" height="31" width="131" border="0" onmouseover="display(11);" onmouseout="display(10);" /></a><br />
<!-- <a href="members.php" title="members"><img src="images/btn-members.gif" alt="members" height="31" width="131" border="0" /></a><br /> -->
<!-- <a href="createacct.php" title="create account"><img src="images/btn-createacct.gif" alt="create account" height="31" width="131" border="0" /></a><br /> -->
<a href="application.php" title="become a provider"><img src="images/btn-provider.gif" name="jobs" alt="become a provider" height="31" width="131" border="0" onmouseover="display(13);" onmouseout="display(12);" /></a><br />
<a href="friends.php" title="our friends"><img src="images/btn-friends.gif" name="friends" alt="our friends" height="31" width="131" border="0" onmouseover="display(15);" onmouseout="display(14);" /></a><br />
<a href="faq.php" title="frequently asked questions"><img src="images/btn-faq.gif" name="faqs" alt="faq" height="31" width="131" border="0" onmouseover="display(17);" onmouseout="display(16);" /></a><br />
<div class="admin-link"><a href="admin.php" title="admin login">admin login</a></div>
<img src="images/blank.gif" alt="" height="25" width="131" />
<?php include("joinmailinglist.php"); ?>
</div>
